version: "3.8"
services:
    flaskapp:
        build: .
        image: titanic-flask:latest
        ports:
            - "5000:5000"
        links:
            - "postgres:psql_db"
        depends_on:
            - psql_db
        environment:
            SECRET_KEY: secret_key
            USE_POSTGRES: 'true'
            POSTGRES_PASSWORD: postgres_docker
            POSTGRES_USER: postgres_docker
            POSTGRES_DB: psql_db

    psql_db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres_docker
            POSTGRES_USER: postgres_docker
        restart: always